logging:
  pattern:
    #控制台输出格式
    console: "%d %-5level %logger : %msg%n"
    #文件输出格式
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.eclipse.jetty: 'WARN'
    org.apache: WARN
    org.apache.catalina.webresources.Cache: ERROR
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
    org.hibernate.jpa.internal: ERROR
    org.hibernate.validator.internal: WARN
    org.springframework: debug
    org.springframework.data.jpa: WARN
    org.springframework.validation: WARN
    org.springframework.web: WARN
    org.springframework.web.socket: WARN

server:
  port: 9000
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: default
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    multipart:
      max-file-size: 3Mb
      max-request-size: 4Mb
  redis:
    database: 10
    secondary-database: 11
    host: 127.0.0.1
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

  mvc:
    throw-exception-if-no-handler-found: true
  session:
    store-type: none

  messages:
    basename: i18n/messages